### ISSUE TITLE
There is no variable named "DEVICE_NAME"

### ISSUE THREAD

**Issue by RaulElevate** [BigDataBoutique/elasticsearch-cloud-deploy#67] opened 2019-07-02 02:27 UTC
Hi, 

this repo has been very helpful. Thanks for that.

However, I'm trying to deploy it and I'm getting this error on Terraform Apply:

`4 errors occurred:
	* data.template_file.data_userdata_script: data.template_file.data_userdata_script: failed to render : <template_file>:91,41-52: Unknown variable; There is no variable named "DEVICE_NAME"., and 2 other diagnostic(s)
	* data.template_file.client_userdata_script: data.template_file.client_userdata_script: failed to render : <template_file>:91,41-52: Unknown variable; There is no variable named "DEVICE_NAME"., and 2 other diagnostic(s)
	* data.template_file.single_node_userdata_script: data.template_file.single_node_userdata_script: failed to render : <template_file>:91,41-52: Unknown variable; There is no variable named "DEVICE_NAME"., and 2 other diagnostic(s)
	* data.template_file.master_userdata_script: data.template_file.master_userdata_script: failed to render : <template_file>:91,41-52: Unknown variable; There is no variable named "DEVICE_NAME"., and 2 other diagnostic(s)`

Any clues about what might be causing it? I have changed the type of instances on AWS. Maybe it's related to it.

**Comment by tsimonyan** [comment] 2019-09-20 07:26
Closing since it's fixed now.
Was caused by shell var being referenced by `${DEVICE_NAME}` instead of `$DEVICE_NAME` which triggered Terraform template render.

**Closed by tsimonyan** 2019-09-20 07:26 UTC
